<?php
$PaymentMethod = $this->paymentMethod;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> edit Payment</title>

</head>
<body>
		
		<?php $this->setTemplate('html/header.phtml')->render();?>
	
<form action="<?php echo $this->getUrl('save')?>" method="post">
		<div class="body1">
			EDIT PAYMENT METHOD
			<button class="body2"><a href="index.php?c=PaymentMethod&a=grid" >Cancel</a></button>
			<button type="submit" class="body2">Save</button>
		</div>

	</div>

	<table class="t1" border="1">
		<tr >
			<td colspan="2"> PaymentMethod Information</td>
		</tr>
		<tr >
			<input type="hidden" name="id" value="<?php echo $PaymentMethod->payment_method_id;?>">
		</tr>
		<tr>
			<td>name : </td>
			<td><input type="text" name="PaymentMethod[name]" value="<?php echo $PaymentMethod->name;?>"></td>
		</tr>
		
		<tr>
			<td>Status : </td>
			<td>
				<select name="PaymentMethod[status]" >
					<?php foreach ($PaymentMethod->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $PaymentMethod->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				
				</select>
		</tr>
		
		

	</table>
		
	</form>
		<?php $this->setTemplate('html/footer.phtml')->render();?>


</body>
</html>


