<?php
$PaymentMethods = $this->paymentMethods;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>payment Grid
	</title>
	
		
</head>
<body>
<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<br><br>

	<div class="body">
		
			<h3>MANAGE PAYMENT METHOD</h3>
			<button class="body2" type="button" name="Add catagories" value="Add catagories"   ><a href="<?php echo $this->getUrl('add') ?>"> Add PaymentMethods  </a> </button>
		</div>
		<div>
			<table class="t1" border="1">
				<tr style="border: 1px solid black;">
					<th>payment_method_id</th>
					<th>name</th>
					<th>status</th>
					<td>Edit</td>
					<td>Delete</td>
				</tr>

				<?php
				foreach($PaymentMethods as $PaymentMethod){


				?>
				<tr>
					<td><?php echo $PaymentMethod->payment_method_id; ?></td>
					<td><?php echo $PaymentMethod->name;?></td>
					<td><?php echo $PaymentMethod->getStatusText(); ?></td>


					<td>
						<a href="<?php echo $this->getUrl('edit',null,['id'=>$PaymentMethod->payment_method_id])?>">
					Edit</a>
					</td>
					<td>
						<a href="<?php echo $this->getUrl('delete',null,['id'=>$PaymentMethod->payment_method_id])?>">
					Delete</a>
					</td>	
				</tr>
				<?php
				}
				?>

			</table>
		
</div>
		<?php include'C:\xampp\htdocs\project\View\html\footer.phtml'; ?>

</body>
</html>

