<style>
.header {
  overflow: hidden;
  background-color: skyblue;
  padding: 20px 10px;
  width: 100%;
}
.header a {
  width: 12%;
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}
.header-right{
    width: 100%;
}
</style>
    <div class="header" >
    <a href="<?php echo $this->getUrl('grid','Product') ?>">Product</a>
    <a href="<?php echo $this->getUrl('grid','Category') ?>">Category</a>
    <a href="<?php echo $this->getUrl('grid','Customer') ?>">Customer</a>
    <a href="<?php echo $this->getUrl('grid','Vendor') ?>">Vendor</a>
    <a href="<?php echo $this->getUrl('grid','Salesman') ?>">Salesman</a>
    <a href="<?php echo $this->getUrl('grid','ShippingMethod') ?>">Shipping Method</a>
    <a href="<?php echo $this->getUrl('grid','PaymentMethod') ?>">Payment Method</a>

</div>


