<?php

$customer = $this->customer;
$customerAddress = $this->customerAddress;


?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Customer</title>
	<style>
		
	</style>
	
		
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<form action="<?php echo $this->getUrl('save')?>" method="post">

	
		<div class="body1">
			EDIT CUSTOMER
			<button class="body2"><a href="<?php echo $this->getUrl('grid') ?>">Cancel</a></button>
			<button type="submit" class="body2">Save</button>
		</div>

	</div>

	<table class="t1" border="1">
		<tr >
			<td colspan="2"> customer Information</td>
		</tr>
		<tr >
			<input type="hidden" name="id" value="<?php echo $customer->customer_id;?>">
		</tr>
		<tr>
			<td>first_name : </td>
			<td><input type="text" name="customer[first_name]" value="<?php echo $customer->first_name;?>"></td>
		</tr>
		<tr>
			<td>last_name : </td>
			<td><input type="text" name="customer[last_name]" value="<?php echo $customer->last_name;?>"></td>
		</tr>
		<tr>
			<td>email : </td>
			<td><input type="text" name="customer[email]" value="<?php echo $customer->email; ?>"></td>
		</tr>
		<tr>
			<td>gender : </td>
			<td><input type="text" name="customer[gender]" value="<?php echo $customer->gender; ?>"></td>
		</tr>
		<tr>
			<td>mobile : </td>
			<td><input type="text" name="customer[mobile]" value="<?php echo $customer->mobile; ?>"></td>
		</tr>
		<tr>
			<td>Status : </td>
			<td>
				<select name="customer[status]" >
					<?php foreach ($customer->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $customer->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
		</tr>

	</table>

	<div>Address Information</div>
		<table>
			<tr>
				<td>Address</td>
				<td><input type="text" name="customerAddress[address]" value="<?php echo $customerAddress->address; ?>"></td>
			</tr>
			<tr>
				<td>City</td>
				<td><input type="text" name="customerAddress[city]" value="<?php echo $customerAddress->city; ?>"></td>
			</tr>
			<tr>
				<td>State</td>
				<td><input type="text" name="customerAddress[state]" value="<?php echo $customerAddress->state; ?>"></td>
			</tr>
			<tr>
				<td>Country</td>
				<td><input type="text" name="customerAddress[country]" value="<?php echo $customerAddress->country; ?>"></td>
			</tr>
			<tr>
				<td>ZIP Code</td>
				<td><input type="text" name="customerAddress[zipcode]" value="<?php echo $customerAddress->zipcode; ?>"></td>
			</tr>
		</table>

	
		
	</form>
	<?php $this->setTemplate('html/footer.phtml')->render();?>


</body>
</html>