<?php

$customers = $this->customers;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Customer Grid
	</title>
	
	
		
</head>
<body>
		<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<br><br>

	<div class="body">
		
			<h3>MANAGE CUSTOMER</h3>
			<button class="body2" type="button" name="Add customer" value="Add customer"   ><a href="<?php echo $this->getUrl('add') ?>">Add customer </a> </button>
		</div>
		<div>
			<table class="t1" border="1" width="100%">
				<tr style="border: 1px solid black;">
					<th>customer_id</th>
					<th>first_name</th>
					<th>last_name</th>
					<th>email</th>
					<th>gender</th>
					<th>mobile</th>
					<th>status</th>
					<th>Edit</a></th>
					<th>Delete</th>
				</tr>
				<?php
				foreach ($customers as $customer ) {
						
				?>
				<tr>
					<td><?php echo $customer->customer_id;?></td>
					<td><?php echo $customer->first_name;?></td>
					<td><?php echo $customer->last_name?></td>
					<td><?php echo $customer->email?></td>
					<td><?php echo $customer->gender?></td>
					<td><?php echo $customer->mobile?></td>
					<td><?php echo $customer->getStatusText(); ?></td>


					<td><a href="<?php echo $this->getUrl('edit',null,['id'=>$customer->customer_id])?>">Edit</a></td>
					<td><a href="<?php echo $this->getUrl('delete',null,['id'=>$customer->customer_id])?>">Delete</a></td>

				</tr>
				<?php 
				}

				 ?>


			</table>
		
</div>
		<?php $this->setTemplate('html/footer.phtml')->render();?>


</body>
</html>

