<?php
$category = $this->category;

// print_r($category);
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Category</title>
	<style>
		
</style>
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>

<form action="<?php echo $this->getUrl('save')?>" method="post">

	
		<div class="body1">
			EDIT CATEGORY
			<button><a href="<?php echo $this->getUrl('grid') ?>">Cancel</a></button>

			<button type="submit" class="body2">Save</button>
		</div>

	</div>

	<table class="t1" border="1">
		<tr >
			<td colspan="2"> category Information</td>
		</tr>
		<tr >
			<input type="hidden" name="id" value="<?php echo $category->category_id;?>">
		</tr>
		<tr>
			<td>name : </td>
			<td><input type="text" name="category[name]" value="<?php echo $category->name ?>"></td>
		</tr>
		<tr>
			<td>Status : </td>
			<td>
				<select name="category[status]">
					<?php foreach ($category->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $category->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
		</tr>
		<tr>
		
			<td>Description : </td>
			<td><textarea name="category[description]" ><?php echo $category->description  ?></textarea></td>
		</tr>
		
		

	</table>
		
	</form>
	<?php $this->setTemplate('html/footer.phtml')->render();?>


</body>
</html>


