<?php
$categories = $this->categories;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Category Grid</title>
	
		<style>
		
</style>
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>


	<br><br>

	<div class="body">
		
			<h3>MANAGE CATEGORIES</h3>
			<button class="body2" type="button" name="Add catagories" value="Add catagories"   ><a href="<?php echo $this->getUrl('add') ?>">Add Categories  </a> </button>
		</div>
		<div>
			<table class="t1" border="1" width="100%">
				<tr style="border: 1px solid black;">
					<th>category_id</th>
					<th>name</th>
					<th>status</th>
					<th>description</th>
					<td>Edit</td>
					<td>Delete</td>
				</tr>

				<?php
				foreach($categories as $category){


				?>
				<tr>
					<td><?php echo $category->category_id ?></td>
					<td><?php echo $category->name ?></td>
					<td><?php echo $category->getStatusText(); ?></td>
					<td><?php echo $category->description ?></td>
					<td><a href="<?php echo $this->getUrl('edit',null,['id'=>$category->category_id])?>">Edit</a></td>
					<td><a href="<?php echo $this->getUrl('delete',null,['id'=>$category->category_id])?>">Delete</a></td>

				</tr>
				<?php
				}
				?>

			</table>
		
</div>
	<?php $this->setTemplate('html/footer.phtml')->render();?>


</body>
</html>

